#!/usr/bin/env python3
"""Regenerate Personal/Books/Library.md and Wishlist.md in an Obsidian vault.

Reads the same JSON exports as regenerate-md.py (`library.json`, `wishlist.json`)
but emits Obsidian-flavored markdown:
- AI-first frontmatter (`date`, `tags`, `ai-first: true`, plus `last-sync`/counts)
- "For future Claude" preamble
- Plain markdown links to Audible product pages (no broken `[[wikilinks]]`)

Sibling to `regenerate-md.py`; doesn't modify it. Intended to be invoked
after the standard sync pipeline by a wrapper script.

Usage:
    python3 regenerate-vault-md.py --out-dir /path/to/vault/Personal/Books
    python3 regenerate-vault-md.py --out-dir <out> --source-dir <dir-with-json>
"""
from __future__ import annotations

import argparse
import json
from collections import Counter
from datetime import datetime
from pathlib import Path

URL_BASE = "https://www.audible.com/pd/"


def fmt_runtime(mins: int | None) -> str:
    if not mins:
        return "?"
    h, m = divmod(int(mins), 60)
    if h and m:
        return f"{h}h {m}m"
    if h:
        return f"{h}h"
    return f"{m}m"


def listening_status(rec: dict) -> str:
    if rec.get("is_finished"):
        return "Finished"
    if (rec.get("percent_complete") or 0) > 0:
        return "In progress"
    return "Not started"


def remaining(rec: dict) -> str:
    runtime = rec.get("runtime_length_min") or 0
    pc = rec.get("percent_complete") or 0
    if not runtime or pc <= 0 or pc >= 100:
        return ""
    left = round(runtime * (100 - pc) / 100)
    return f"{fmt_runtime(left)} left"


def title_link(rec: dict) -> str:
    return f"[{rec['title']}]({URL_BASE}{rec['asin']})"


def render_library_vault(records: list[dict], today_iso: str, sync_iso: str) -> str:
    by_status: dict[str, list[dict]] = {"Finished": [], "In progress": [], "Not started": []}
    for r in records:
        by_status[listening_status(r)].append(r)
    for v in by_status.values():
        v.sort(key=lambda r: r["title"].lower())

    counts = {k: len(v) for k, v in by_status.items()}

    fm = (
        "---\n"
        f"date: {today_iso}\n"
        "tags:\n"
        "  - personal-book\n"
        "  - library\n"
        "ai-first: true\n"
        f"last-sync: {sync_iso}\n"
        f"total-titles: {len(records)}\n"
        f"finished: {counts['Finished']}\n"
        f"in-progress: {counts['In progress']}\n"
        f"not-started: {counts['Not started']}\n"
        "---\n\n"
    )

    preamble = (
        "## For future Claude\n\n"
        f"Albert's Audible library snapshot as of {today_iso} ({len(records)} titles total: "
        f"{counts['Finished']} finished, {counts['In progress']} in progress, "
        f"{counts['Not started']} not started). Auto-regenerated by the `obsidian-books-sync` "
        "schedule from `~/career/books/`. Use this when answering questions about reading "
        "history, in-progress books, what to recommend next, or what genres/authors land. "
        "Numeric counts and `last-sync` in frontmatter are queryable; per-title detail is "
        "below grouped by listening status.\n\n"
        "---\n\n"
    )

    body: list[str] = []
    body.append("# Audible Library")
    body.append("")
    body.append(f"_Snapshot: {today_iso} · Source: `audible library export` · Total: **{len(records)}**_")
    body.append("")
    body.append("| Status | Count |")
    body.append("|---|---:|")
    for k in ("Finished", "In progress", "Not started"):
        body.append(f"| {k} | {counts[k]} |")
    body.append("")
    body.append("Legend: `[F]` Finished · `[~]` In progress · `[ ]` Not started")
    body.append("")

    for status in ("In progress", "Not started", "Finished"):
        items = by_status[status]
        body.append(f"## {status} ({len(items)})")
        body.append("")
        for r in items:
            tag = {"Finished": "[F]", "In progress": "[~]", "Not started": "[ ]"}[status]
            body.append(f"### {tag} {title_link(r)}")
            sub = r.get("subtitle")
            if sub:
                body.append(f"_{sub}_")
            body.append("")
            authors = r.get("authors") or "—"
            narrators = r.get("narrators") or "—"
            body.append(f"- **Authors:** {authors}")
            body.append(f"- **Narrators:** {narrators}")
            length = fmt_runtime(r.get("runtime_length_min"))
            left = remaining(r)
            length_line = f"- **Length:** {length}"
            if left:
                length_line += f" · {left}"
            pc = r.get("percent_complete")
            if pc is not None and not r.get("is_finished"):
                length_line += f" · {pc:.0f}%"
            body.append(length_line)
            series = r.get("series_title")
            if series:
                seq = r.get("series_sequence")
                body.append(f"- **Series:** {series}" + (f" #{seq}" if seq else ""))
            genres = r.get("genres")
            if genres:
                body.append(f"- **Genres:** {genres}")
            rating = r.get("rating")
            num = r.get("num_ratings")
            if rating and rating != "-":
                body.append(f"- **Rating:** {rating} ({num} ratings)")
            added = r.get("date_added") or r.get("purchase_date")
            if added:
                body.append(f"- **Added:** {added[:10]}")
            release = r.get("release_date")
            if release:
                body.append(f"- **Released:** {release[:10]}")
            body.append(f"- **ASIN:** `{r['asin']}`")
            body.append("")

    return fm + preamble + "\n".join(body).rstrip() + "\n"


def render_wishlist_vault(records: list[dict], today_iso: str, sync_iso: str) -> str:
    records_sorted = sorted(
        records,
        key=lambda r: (r.get("date_added") or "", r["title"]),
        reverse=True,
    )

    fm = (
        "---\n"
        f"date: {today_iso}\n"
        "tags:\n"
        "  - personal-book\n"
        "  - wishlist\n"
        "ai-first: true\n"
        f"last-sync: {sync_iso}\n"
        f"total-items: {len(records)}\n"
        "---\n\n"
    )

    preamble = (
        "## For future Claude\n\n"
        f"Albert's Audible wishlist snapshot as of {today_iso} ({len(records)} items). "
        "Auto-regenerated by `obsidian-books-sync` from `~/career/books/`. Sorted newest "
        "additions first. Use this for recommendation conversations, to track what they're "
        "considering vs what they've actually bought, or to spot wishlist drift (items "
        "lingering for months without action).\n\n"
        "---\n\n"
    )

    body: list[str] = []
    body.append("# Audible Wishlist")
    body.append("")
    body.append(f"_Snapshot: {today_iso} · Source: `audible wishlist export` · Total: **{len(records)}**_")
    body.append("")
    body.append("Sorted by date added (newest first).")
    body.append("")
    body.append("| # | Title | Author | Length | Released | Rating |")
    body.append("|---:|---|---|---|---|---:|")
    for i, r in enumerate(records_sorted, 1):
        rating = r.get("rating") or "-"
        num = r.get("num_ratings") or "-"
        rating_cell = f"{rating} ({num})" if rating != "-" else "-"
        title_cell = title_link(r)
        sub = r.get("subtitle")
        if sub:
            title_cell += f"<br/><sub>{sub}</sub>"
        length = fmt_runtime(r.get("runtime_length_min"))
        released = (r.get("release_date") or "")[:10] or "-"
        body.append(
            f"| {i} | {title_cell} | {r.get('authors') or '-'} | {length} | {released} | {rating_cell} |"
        )

    return fm + preamble + "\n".join(body).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Emit Obsidian-flavored Audible library/wishlist markdown.")
    parser.add_argument("--out-dir", type=Path, required=True,
                        help="Target directory in the vault (e.g. ~/Documents/<vault>/Personal/Books).")
    parser.add_argument("--source-dir", type=Path, default=None,
                        help="Directory containing library.json + wishlist.json (default: parent of script dir).")
    args = parser.parse_args()

    src = args.source_dir or Path(__file__).resolve().parent.parent
    lib_json = src / "library.json"
    wl_json = src / "wishlist.json"

    if not lib_json.exists():
        raise SystemExit(f"missing {lib_json} — run: audible library export -f json")
    if not wl_json.exists():
        raise SystemExit(f"missing {wl_json} — run: audible wishlist export -f json")

    lib = json.loads(lib_json.read_text())
    wl = json.loads(wl_json.read_text())

    today_iso = datetime.now().date().isoformat()
    sync_iso = datetime.now().isoformat(timespec="seconds")

    out = args.out_dir.expanduser().resolve()
    out.mkdir(parents=True, exist_ok=True)

    (out / "Library.md").write_text(render_library_vault(lib, today_iso, sync_iso))
    (out / "Wishlist.md").write_text(render_wishlist_vault(wl, today_iso, sync_iso))

    counts = Counter(listening_status(r) for r in lib)
    print(f"Wrote {out}/Library.md — {len(lib)} titles ({dict(counts)})")
    print(f"Wrote {out}/Wishlist.md — {len(wl)} items")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
